redsys_homepage:
    pattern:  /redsys
    defaults: { _controller: RedsysBundle:Redsys:execute }
    requirements:
            _method:  GET

redsys_result:
    pattern:  /redsys/result
    defaults: { _controller: RedsysBundle:Redsys:result }
    requirements:
            _method:  POST
