services:

   redsys.form.type.wrapper:
        class: %redsys.form.type.wrapper.class%
        arguments:
            form.factory: @form.factory
            payment.bridge: @payment.bridge
            redsys.merchant.code: %redsys.merchant.code%
            redsys.secret.key: %redsys.secret.key%
            redsys.url: %redsys.url%
        tags:
            - { name: form.type, alias: pagosonlinegateway_view }

   redsys.manager:
        class: %redsys.manager.class%
        arguments:
            payment.event.dispatcher: @payment.event.dispatcher
            redsys.form.type.wrapper: @redsys.form.type.wrapper
            payment.bridge: @payment.bridge
            templating: @templating
            redsys.secret.key: %redsys.secret.key%

   redsys.routes.loader:
       class: %redsys.routes.loader.class%
       tags:
           - { name: routing.loader }
